### ISSUE TITLE
Any way to reduce quantity of a producto without removing it?

### ISSUE THREAD

**Issue by rusosnith** [peet86/cart-localstorage#1]
Adding negative quantity does not work

**Comment by peet86** [comment]
Atm you can do this: 
```
update(id,'quantity', get(id).quantity - 1) 
```
But I agree, there should be an increase / decrease methods. 
I will implement them and extend the library.

**Comment by peet86** [comment]
@rusosnith I've added a new method called "quantity". One can use this to increase/decrease the quantity value without querying the actual value of the product. 

You can use it like this: 

```
quantity(id,1)
quantity(id,-1)
```

**Comment by rusosnith** [comment]
that is awesome indeed! thanks!
