### ISSUE TITLE
Custom reducer function example for Total

### ISSUE THREAD

**Issue by bkoranda** [peet86/cart-localstorage#16]
Thank you for this library.

>>> By default returns with the total price:
>>> or you can pass a custom reducer function to have full control over the calculation.

Do you have an example of using a reducer function for total? I'm trying to implement applying "discount" functionality (ie: 10% off the subtotal) but not sure what the best way to implement that would be. 

Thank you in advance if you are able to recommend anything.

**Comment by peet86** [comment]
You can do something like this: 

```javascript
const myReducer = (sum, product) => (sum += (product.price * product.quantity * product.discount))
total(myReducer)
```

**Comment by peet86** [comment]
@peet86 todo: add example to the readme / demo.
