### ISSUE TITLE
Add sumQuantity feature

### ISSUE THREAD

**Issue by Brianmartinezsebas** [peet86/cart-localstorage#24]
you can add a count() function that return the number of items that are in list()
this function is necessary since with "list().length" we only get the items, we must add the quantity of products

**Comment by peet86** [comment]
Good idea. I will call it itemCount or sumQuantity or something like that make it clear what it actually does.

**Comment by peet86** [comment]
@Brianmartinezsebas btw I've just realized you can use `total()` for this.. 
total([reducer]) is able to accept a custom `[reducer]` function. I think in your case should do the job:  `(sum, product) => (sum += product.quantity, 0)`

**Comment by Brianmartinezsebas** [comment]
and what do you think of a validate() function that checks if a value is correct (check if the price is the same with the database) example:
validate(product_id, price, value_price)
that according to the id (product_id) verify that the "price" field is equal to "value_price" if it is equal it is not changed, but if it is not equal it is changed to the value of "value_price".

**Comment by omerhazir** [comment]
Hello; To see the number of products added to the cart after each add or remove operation, what kind of addition should you make to your code?

I have solved it by adding the following code to my own project.

`
$('.total').bind('DOMSubtreeModified', function(){
Tpl=0
$("#SepetSay").show()
$(".St").each(function () { 
  var T = parseInt($(this).text()); 
  Tpl=Tpl+ T 
}); 
$("#SepetSay").text(Tpl)
if(Tpl==0){$("#SepetSay").hide()}
`

But there must be an easier way. I am waiting for your support on this matter.

Example Working Code: https://codepen.io/omerhazir/pen/XWoPZVV

**Comment by peet86** [comment]
I've [extended the demo ](https://peet86.github.io/cart-localstorage/)with the simplest solution I could come up with..  I did this only to demonstrate how easy to access to the products and do _anything_ with them rendering-time..

Also as I mentioned earlier there is a way to pass a reducer to the total() function which you can use to summarize any product attribute.

Sample code: 
`const totalQuantity = total((sum, product) => (sum += product.quantity), 0)`

**Comment by omerhazir** [comment]
Thank you for responding very quickly and producing a solution. Now your application is much more useful.
