### ISSUE TITLE
Cant use in browser via cdn

### ISSUE THREAD

**Issue by omkar-tenkale** [peet86/cart-localstorage#6]
When using

	const myproduct = {id: 3, name: "Vans", price: 75}
	add(myproduct, 2);

ReferenceError: _typeof is not definedcart-localstorage.min.js:1:12
    <anonymous> https://unpkg.com/cart-localstorage@1.1.2/dist/cart-localstorage.min.js:1

Imported in html as

<script src="https://unpkg.com/cart-localstorage@1.1.2/dist/cart-localstorage.min.js" type="text/javascript"></script>

**Comment by peet86** [comment]
Hey omkar-tenkale, 

If you include the lib directly (via cdn) you need to use the cartLS instance.
Here is a working example: 
```
document.addEventListener("DOMContentLoaded", function(){
    const myproduct = {id: 3, name: "Vans", price: 75}
    cartLS.add(myproduct, 2);
    console.log(cartLS.total())
})

```

Also please use the latest version (1.1.4): 

```
<script src="https://unpkg.com/cart-localstorage@1.1.2/dist/cart-localstorage.min.js" type="text/javascript"></script>
```
