### ISSUE TITLE
quantity update not working

### ISSUE THREAD

**Issue by Brecht272727** [peet86/cart-localstorage#9]
If i use the cartLS.quantity(id,1); or cartLS.quantity(id,-1); the quantity is going p.e. from 7 by default to 71 instead of 8
What is going wrong?

**Comment by mcanguler** [comment]
> If i use the cartLS.quantity(id,1); or cartLS.quantity(id,-1); the quantity is going p.e. from 7 by default to 71 instead of 8
> What is going wrong?

this code is working

 var $input = $('#quantityInpt' + data.id).val();
        $input = parseInt($input);
        cartLS.add({id: data.id, name: data.name, price: data.price}, $input);
